// Generated by scripts/make-glyph-atlas.mjs - do not edit. Regenerate with `pnpm icon`.
// Logical points at menu bar scale, matching assets/tray/glyphs*.png.
export const GLYPH_ORDER = "0123456789ABDR-";
export const GLYPH_CELL = 11;
export const GLYPH_BASELINE = 16;
export const GLYPH_INK_HEIGHT = 10.23;
export const GLYPH_ADVANCE = {
  "0": 8.92,
  "1": 6.57,
  "2": 8.48,
  "3": 8.83,
  "4": 9.06,
  "5": 8.72,
  "6": 8.98,
  "7": 7.98,
  "8": 9.05,
  "9": 8.98,
  "A": 9.56,
  "B": 9.22,
  "D": 10.12,
  "R": 9.19,
  "-": 6.51
};
